### PR TITLE
show free resource conversion

### PR DESCRIPTION
**Pull request by zeitlinger**
show free resource conversion

image

### CODE REVIEW

**Comment by coyotte508** [comment]
Nice :) 

I'll wait a bit before publishing the next version - I published a lot these last few days ;)

**Comment by zeitlinger** [comment]
Sure, didn't know there's a manual step.

**Comment by zeitlinger** [comment]
I tried adding tooltips to the individual icons, but that somehow didn't work.

**Comment by coyotte508** [comment]
I could probably automate part of it with github actions

**Comment by zeitlinger** [comment]
image

caused this bug - empty instead of 0

**Pull request merged**
